# -*- coding: utf-8 -*-
"""Fake_News_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bbx9_jytAdB7nCcSCvNI0PMHstVTNgfu
"""

!pip install nltk

import pandas as pd
import numpy as np
import nltk
import re
import string

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sns

nltk.download('stopwords')



from google.colab import drive
drive.mount('/content/drive')

!unzip archive.zip

fake = pd.read_csv("Fake.csv")
true = pd.read_csv("True.csv")

fake["label"] = 0
true["label"] = 1

data = pd.concat([fake, true])

data = data.sample(frac=1, random_state=42)

data.head()

print(data.shape)

data.head()

stemmer = PorterStemmer()

stop_words = set(stopwords.words("english"))

def clean_text(text):

    text = text.lower()

    text = re.sub(r'https?://\S+','',text)

    text = re.sub(r'<.*?>','',text)

    text = re.sub(r'[^a-zA-Z]',' ',text)

    words = text.split()

    words = [stemmer.stem(word) for word in words if word not in stop_words]

    return " ".join(words)

# Create content column
data["content"] = data["title"] + " " + data["text"]

# Clean text
data["content"] = data["content"].apply(clean_text)

# Features and labels
X = data["content"]
y = data["label"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(max_features=5000)
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

# Train Model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predictions
pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, pred)
print("Accuracy:", accuracy)

# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, pred))

# Confusion Matrix
cm = confusion_matrix(y_test, pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

def predict_news(news):
    cleaned = clean_text(news)
    vector = vectorizer.transform([cleaned])

    prediction = model.predict(vector)[0]
    probability = model.predict_proba(vector)[0]

    if prediction == 1:
        print("🟢 Real News")
        print(f"Confidence: {probability[1]*100:.2f}%")
    else:
        print("🔴 Fake News")
        print(f"Confidence: {probability[0]*100:.2f}%")

predict_news("NASA launched a new satellite into space.")

predict_news("Aliens landed in New York yesterday.")

predict_news("President Donald Trump met with lawmakers in Washington to discuss tax reform.")